db_file: "bot.db"

connect_db: "host=%s port=%s user=%s password=%s dbname=%s sslmode=%s"
host: "db"
port: "5432"

sms_link: "https://sms.ru/sms/send?api_id=%s&to=%s&msg=%s&json=1"
discounts_url: "https://bostonwears.ru/discounts"
balance: "Текущий баланс: %s"
catalog_file: "/root/shared_files/catalog.pdf"
path_to_xml: "/root/shared_files/fiz_lica.xml"
delimiter: "--------------------------------\n"


change_request: "BEGIN; ALTER TABLE client_repository RENAME TO client_repository_old; ALTER TABLE client_repository_new RENAME TO client_repository; COMMIT;"
create_table: "CREATE TABLE IF NOT EXISTS client_repository_new (id SERIAL PRIMARY KEY, client_name VARCHAR(60), phone_number VARCHAR(20) NOT NULL, bonus INT NOT NULL);"

reserved_words:
  store_addr:
    mayakovskogo: "Маяковского"
    ryleyeva: "Рылеева"
    pushkarovskoye: "Пушкаревское"
    optimus: "Оптимус"
    sovremennik: "Современник"
    promyshlennaya: "Промышленная"
    discount_center: "Буинская"

messages:
  responses:
    code_sent: "На указанный номер телефона отправлено смс с кодом подтверждения. Введите его"
    need_number: "Пожалуйста, введите свой номер телефона для авторизации в формате 79123456789"
    success_auth: "Успешная авторизация. Теперь Вы можете воспользоваться всеми функциями бота"
    text_start: "Привет, чтобы воспользоваться всеми функциями бота, необходимо пройти процесс верификации. Для этого отправьте в бот свой номер телефон в таком формате: 79999999999. После этого вам придет смс с 4-значным кодом, который необходимо будет отправить в чат."
    delete_success: "Команда успешно выполнена. Введите номер телефона."
    start_already_logged: "Поздравляем! Вы успешно авторизовались, поэтому Вы можете воспользоваться всеми возможностями бота, среди которых:\n1)  Контакты\n2)  Ваш баланс\n3)  Актуальные акции\n4)  Новинки\n5)  Каталог школьной формы\n6)  Адреса Магазинов"
    already_logged: "Вы уже авторизованы."
    select_store: "Выберите магазин"
    novelties: "Весь ассортимент и актуальную информацию вы можете узнать по этой ссылке:\nhttps://bostonwears.ru/"
    contacts: "Контакты:\n\nОфис: +7 (8422) 44-97-55\n\nОптовый отдел: 8 (800) 222-25-10 (доб 2)\n\nРозничный отдел: 8 (800) 222-25-10 (доб 1)\n\nE-mail: info@boston73.ru"
  errors:
    need_code: "Ранее на указанный номер телефона был отправлен 4-значный проверочный код. Пожалуйста введите его"
    access_denied: "Вас нет в списке наших клиентов. Пожалуйста, обратитесь в ближайший магазин Boston"
    unauthorized: "Вы не авторизованы. Используйте команду /start"
    cant_create_token: "Ошибка при создании токена."
    unknown_error: "Произошла неизвестная ошибка."
    number_already_auth: "Этот номер телефона уже зарегистрирован"
    cant_delete_data_from_DB: "Ошибка внутри сервера, попробуйте еще раз"
    check_user_status: "Ошибка при получении данных о состоянии пользователя, попробуйте еще раз."
    cant_send_sms_to_phone: "Ошибка при отправке смс на номер телефона. Попробуйте еще раз"
    cant_save_to_DB: "Произошла ошибка при сохранении данных. Необходима проверка репозиториев."
    cant_get_data_from_DB: "Ошибка при получении данных с БД"
    cant_send_message: "Произошла ошибка при отравке сообщения пользователю в чат\n"
  addresses:
    mayakovskogo: "г. Ульяновск, пр. Нариманова, 41\n+7 (8422) 46-20-71\nОстановка Маяковского\nГрафик работы 10:00-19:00\nhttps://yandex.ru/maps/-/C2t6BrR"
    ryleyeva: "г. Ульяновск, ул. Радищева, 66\n+7 (8422) 44-37-30\nОстановка Рылеева\nГрафик работы 10:00-19:00\nhttps://yandex.ru/maps/-/C2xEjja"
    pushkarovskoye: "г. Ульяновск, Московское шоссе, 100\n+7 (8422) 58-22-19\nОстановка Пушкаревское кольцо\nГрафик работы 10:00-19:00\nhttps://yandex.ru/maps/-/C2xIVya"
    optimus: "г. Ульяновск, пр. Ульяновск, 13а, ТЦ Бостон\n+7 (8422) 26-72-22\nОстановка ТЦ Оптимус\nГрафик работы 10:00-19:00\nhttps://yandex.ru/maps/-/C2xMqfQ"
    sovremennik: "г. Ульяновск, пр. Гая, 82\n+7 (8422) 38-82-71\nОстановка Современник\nГрафик работы 10:00-19:00\nhttps://yandex.ru/maps/-/C2xMR5C"
    promyshlennaya: "г. Ульяновск, ул. Рябикова, 32\n+7 (8422) 69-20-22\nОстановка Промышленная\nГрафик работы 10:00-19:00\nhttps://yandex.ru/maps/-/C2xMfhD"
    discount_center: "г. Ульяновск, ул. Буинская, 22\n+7 (9372) 75-25-23\nОстановка Памятник Нариманову\nГрафик работы 10:00-19:00\nhttps://yandex.ru/maps/-/C2xY5dD"
